---
title: "Task 1"
author: "Amelia Ritger"
date: "2/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In ~ 400 - 500 words, prepare a brief, well-written statement: 

To me, the goal of open science is accountability, transparency, and engagement. When (m)any person knows their work is being looked at by another person (or the possibility is present), it is more likely that said person will do better (or, at the very least, truthful) work. Likewise, there is less room for abuse of power or resources when research products such as data, code, and analysis are made public. 

incentive

is less of a possibility that bad work will 

- What are some important goals of “open science” and how do they benefit researchers and environmental scientists? 

accountability (to researchers to do good trustworthy work - if someone is checking your work or you know that is a possibility, you will be less likely to do bad stuff)
transparency (to researchers to do what they say they're going to do - less room for abuse of power/funding/resources)
it allows for greater sharing of ideas, collaboration, creativity, more diverse perspectives by encouraging doing science in a way that is more accessible to people outside the field
open access means more eyes and more citations


Data sharing
correlates with fewer reporting errors, compared
to papers with unavailable data
(Wicherts, 2016) mckiernan et al 2016 elife

- What are some problems with how open science is currently approached regarding inclusiveness, equity and accessibility?

It is not mandatory for publishing or receiving funding
It is not taught or required to be taught unless you seek it out
The idea has been created/developed by humans and therefore there is inherent human error (just like technology is imbued with error of the humans that created it)
re: open access publishing - it costs money to publish open access, and a lot of people don't have thousands of dollars to drop! How do we continue with journal publications in a society where the editors, etc, are DONATING a significant portion of their time if we are against for-profit journals? maybe the program needs a complete restructuring??
To be totally open science you need to have 1) money 2) no competition 3) job security so no fear of retribution for reviews 4) time to totally organize your data/code and make it accessible to everyone
Science is still a jargon heavy field, so in that direction we need to make science writing more focused on open science communication 
Repeatibility - a goal of open science - is near impossible in today's scientific culture. no one repeats experiments.... they just publish and move on. Unlike the olden days where separate labs repeat experiments etc. EXCEPT for the most recent coral reef fish behavior paper!!
When you are not in a research insitution it is near impossible to participate in science - to get access to papers, funding to publish open access...
impace factor matters

- Describe the tools, skills and approaches you are using to make your work more reproducible and open (at a level that makes sense for you - e.g. within research groups, with your adviser, sharing with the public, etc.)

Github!! R code annotations. Pictures and twitter.
Make my paper public on personal website, research gate, ...
Scientific outreach, public talks
Collaboration with people in different departments

- Describe limitations of your current data science work or workflow regarding openness, inclusiveness and accessibility. What are some ways that you could overcome those limitations moving forward in a career beyond UCSB?

I have written peer reviews where I had the option to provide my name and opted not to, because I am early on in my career and am concerned about how my review might affect my career moving forward. 
I would like to provide all my data all the time but I have had exposure to labs where "getting scooped" was a legitimate concern and unfortunately because I have been scooped before and the scientific field inherently awards those who "discover something first" (and publish it first)  --- THINK DARWIN --- then things MUST be kept private.
I would like to get better about making my figures more open science! In terms of having a figure my parents can understand - there is an inherent limitation and a skill to be developed where you are providing the same level of detail and information, but it is more accessible to a broader audience.
I used to have a blog, I would like to do something like that again - or like Science Friday podcast or etc - where I describe my research to a broader audience.
I would like to publish open access and need to seek out funding or seek out journals that do it without a fee more